### ISSUE TITLE
separate tests and helper modules

### ISSUE THREAD

**Issue by sobolevn** [arjan/decorator#9]
This is such a cool library! Thanks for it.

When I have started looking through tests, one thing caught my eye: mixing tests and helper modules together. In general they are divided. What do you think of it?

If that fine by you, I will send a PR.

**Comment by arjan** [comment]
Do you mean putting the decorator implementations in a separate file? I'm not sure sure about that because this way it's clear that the tests are testing what the decorators are producing, if you know what I mean.

It makes sense to split the test case into several separate cases, with one decorator module and one module using the decorators per test case. The file is indeed quite large now.
Something like:

- `decorator/basic_test.exs`
- `decorator/function_result_test.exs`
- `decorator/multiple_clauses_test.exs`
- etc..
